name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: auto

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3.5.3

    - name: Test Output
      run: |
        set -e
        echo "Hello Wusel"
        echo "Hello Wusel (Summary)" >> "$GITHUB_STEP_SUMMARY"

    - name: Build
      run: |
        set -e unset
        set -e errexit
        set -e pipefail

        cargo build --verbose

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3

    - name: Run tests
      run: |
        set -e unset
        set -e errexit
        set -e pipefail

        echo "# Test Results :rocket:" >> "$GITHUB_STEP_SUMMARY"

        cargo test --verbose \
        2>/dev/null \
        >> "$GITHUB_STEP_SUMMARY"

