name: Rust Update

on:
  schedule:
    - cron: '0 4 1 * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: auto

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    outputs:
      updates: ${{ steps.rust-update.outputs.updates }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3

    - name: Rust Update
      id: rust-update
      run: |
        set -e unset
        set -e errexit
        set -e pipefail

        echo "# Update Updates :heavy_check_mark:" >> "$GITHUB_STEP_SUMMARY"

        # random delimiter
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)

        echo "updates<<$EOF" >> "$GITHUB_ENV"
        cargo update --verbose 2>&1 \
        | tee -a "$GITHUB_ENV" \
        | tee -a "$GITHUB_STEP_SUMMARY"

        echo "$EOF" >> "$GITHUB_ENV"

        # summary also to output.
        cat "$GITHUB_ENV" >> GITHUB_OUTPUT

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.1
      with:
        commit-message: "Cargo Update"
        delete-branch: true
        title: Update Dependencies
        labels: bot
        body: |
          ${{ needs.update-dependencies.outputs.updates }}

          Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        branch: update-dependenies

    - name: Check if PR built
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Created new Pull Request: ${{ steps.cpr.pull-request-url }}" \
        >> "$GITHUB_STEP_SUMMARY"

